### ISSUE TITLE
Why are is loss being preprocessed?

### ISSUE THREAD

**Issue by brando90** [markdtw/meta-learning-lstm-pytorch#4]
Why are is loss being preprocessed? it's already a log quantity and applying something like log(|x|)/p seems very weird to me. Any insights?

**Comment by brando90** [comment]
Or was that just how the original code in lua/torch/paper did it?

**Comment by markdtw** [comment]
losses/gradients preprocessing is discussed in Sec 3.2 in the paper.

**Comment by brando90** [comment]
> losses/gradients preprocessing is discussed in Sec 3.2 in the paper.

but thats weird, why would that make sense?
